include $(KEYBOARD_PATH_2)/qmk-vim/rules.mk

SPLIT_KEYBOARD = yes
# STENO_ENABLE = yes
STENO_PROTOCOL = geminipr
CAPS_WORD_ENABLE = yes
SEND_STRING_ENABLE = yes
COMBO_ENABLE = yes

# CONSOLE_ENABLE = yes

